Аккордеон
js-tasks-ru/htmlcss-20240216_akbashev-ar6 pull request #4
Opened 2024-02-25 18:46 UTC by DbrmnPhrh

2024-02-25 18:46 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-02-27 13:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-02-28 10:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-04 20:56 UTC, GSemikozov requested changes

2024-03-04 20:56 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  max-width: 400px;
лишнее

2024-03-04 20:56 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  border: 1px solid #ccc;
цвет бордера не по макету

2024-03-04 20:56 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  padding: 10px;
не по макету

2024-03-04 20:56 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  margin-bottom: 10px;
8

2024-03-04 20:56 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  font-weight: bold;
а еще font-family, font-size, line-height

2024-03-04 20:56 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  padding: 10px 40px 10px 10px;
общих паддингов на уровне .accordion__item хватит

2024-03-04 20:56 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  margin-top: 10px;
16

2024-03-04 20:56 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  padding: 10px 10px;
не надо

2024-03-04 20:56 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  padding: 10px;
и когда .accordion__item[open] - снизу паддинг 32

2024-03-07 14:39 UTC, DbrmnPhrh commented on 03-lection1/02-accordion/accordion.css
> +  padding: 10px;
наверное имелось ввиду .accordion__details[open], добавил

2024-03-07 14:39 UTC, DbrmnPhrh commented on 03-lection1/02-accordion/accordion.css
> +  margin-bottom: 10px;
?

2024-03-12 10:10 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  margin-bottom: 10px;
margin-bottom: 8px

2024-03-12 10:13 UTC, GSemikozov requested changes

2024-03-12 10:13 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  width: 730px;
ширину ограничивать не нужно

2024-03-12 10:13 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  padding: 10px 10px;
`24px 32px`

2024-03-12 10:13 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item {
все стили этого элемента можно перенести в __details а сам элемент тогда будет лишним

2024-03-18 15:49 UTC, DbrmnPhrh commented on 03-lection1/02-accordion/accordion.css
> +  width: 730px;
Ограничивал в соответствии с макетом, ширину убрал, но теперь растянуто на всю страницу

2024-03-20 13:46 UTC, GSemikozov approved these changes

2024-03-20 13:46 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2024-03-20 15:27 UTC, GSemikozov approved these changes

2024-03-20 15:27 UTC, merged