Гистограмма
js-tasks-ru/htmlcss-20240216_akbashev-ar6 pull request #5
Opened 2024-03-02 07:21 UTC by DbrmnPhrh

2024-03-02 07:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-12 10:24 UTC, GSemikozov requested changes

2024-03-12 10:24 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  width: 354px;
ширину и высоту удаляем

2024-03-12 10:24 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  padding: 15px 20px;
`16px 24px 24px`

2024-03-12 10:24 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  top: 20px;
марджины и свойства для внешнего позиционирования на уровне блока не задаем

2024-03-12 10:24 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                    <div class="header__title">
histogram__title

2024-03-12 10:24 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                        <a class='header__filter' href='#'>View all</a>
histogram__link

2024-03-12 10:24 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                    <div class="header__orders-count">
histogram__orders-count

2024-03-12 10:24 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                        <h4>50254</h4>
класс вешаем сюда, не нужно заворачивать в лишний враппер

2024-03-12 10:24 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.bar {
histogram__bar

2024-03-12 10:24 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  width: calc(100% / 30);
у нас может быть разное количество колонок

2024-03-12 10:24 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  margin-right: 1px;
тогда обнулим у :last-child?

2024-03-12 10:24 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  height: 100%;
лишнее (высота должна быть 50px)

2024-03-12 10:24 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  width: 100%;
лишнее

2024-03-12 10:24 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__body {
mergin-top: 39px

2024-03-20 15:08 UTC, GSemikozov requested changes

2024-03-20 15:08 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  width: 354px;
не исправлено

2024-03-20 15:11 UTC, GSemikozov requested changes

2024-03-20 15:11 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  top: 20px;
top + left - удалить

2024-03-20 15:11 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  flex-direction: column;
одновремнно грид и флекс?) что-то одно

2024-03-20 15:11 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  top: 20px;
хотя я понял идею. Но контейнер как враппер компонента надо описывать в отдельном файле стилей, не в файле стилей компонента)

2024-03-20 15:11 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  border-radius: 6px;
8px

2024-03-20 15:11 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  color: var(--blue);
margin-top: 3px

2024-03-20 15:11 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                            <span>Total orders</span>
какие стили у этого текстового элемента?

2024-03-24 14:37 UTC, GSemikozov approved these changes

2024-03-24 14:37 UTC, merged