Календарь
js-tasks-ru/htmlcss-20240216_akbashev-ar6 pull request #7
Opened 2024-03-08 07:09 UTC by DbrmnPhrh

2024-03-08 07:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-12 10:16 UTC, GSemikozov requested changes

2024-03-12 10:16 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  padding: 28px 36px;
`28 26 32`

2024-03-12 10:16 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__item.calendar__item_day {
.calendar__item_day

2024-03-12 10:16 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__item.calendar__select_start-end {
.calendar__select_start-end

2024-03-12 10:16 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__item.calendar__select_range {
.calendar__select_range

2024-03-20 15:14 UTC, GSemikozov requested changes

2024-03-20 15:14 UTC, GSemikozov commented on 05-lection3/03-calendar/index.html
> +            <h2 class="calendar__title">April 2024</h2>
h5

2024-03-24 14:39 UTC, GSemikozov approved these changes

2024-03-24 14:39 UTC, merged