Аватар
js-tasks-ru/htmlcss-20240216_akbashev-ar6 pull request #9
Opened 2024-03-17 17:25 UTC by DbrmnPhrh

2024-03-17 17:26 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-18 15:34 UTC, GSemikozov requested changes

2024-03-18 15:34 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.container {
не часть блока, удалим

2024-03-18 15:34 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +  width: 102px;
100%

2024-03-18 15:34 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +  height: 102px;
100%

2024-03-18 15:34 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar__bg {
лишнее, удалим

2024-03-18 15:34 UTC, GSemikozov commented on 06-lection4/01-avatar/index.html
> +                <div class="avatar__bg">
если через фон, тогда зачем img?)

2024-03-18 15:34 UTC, GSemikozov commented on 06-lection4/01-avatar/index.html
> +                <div class="avatar__img">
лишняя обертка, класс avatar__img сразу вешаем на img

2024-03-18 16:42 UTC, DbrmnPhrh commented on 06-lection4/01-avatar/index.html
> +                <div class="avatar__bg">
сделал 2 варианта просто, ок удалю

2024-03-18 16:50 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-18 16:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-18 16:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-18 16:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-18 16:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-18 16:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-20 13:46 UTC, GSemikozov approved these changes

2024-03-20 13:46 UTC, merged